name: SkywarsUnlimited
version: 1.0.1 BETA
description: SkywarsUnlimited Plugin by MeLays
author: MeLays
website: http://melays.de/
main: de.melays.swunlimited.Main
softdepend: [StatsAPI,Vault,SymptaFriends,Citizens]
commands:
  sw:
    description: Manage the BedwarsUnlimited Plugin
    aliases: [skywars , swunlimited , skywarsunlimited]
    usage: /bw help
  group:
    description: SkywarsUnlimited Groups
    aliases: [group,groups,party,p,g]
    usage: /group help
  leave:
    description: SkywarsUnlimited Leave
    aliases: [l,hub,lobby]
    usage: /leave
  start:
    description: SkywarsUnlimited Start
    aliases: []
    usage: /start
  spectate:
    description: SkywarsUnlimited Spectate
    aliases: []
    usage: /spectate